//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int EId { get; set; }
        public string EName { get; set; }
        public string EDesig { get; set; }
        public System.DateTime EDoj { get; set; }
    }
}
